=== valeryyask/KYAR-1-sem/Лабораторная работа №12/doc3.xsd
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<xs:schema xmlns:xs ="http://www.w3.org/2001/XMLSchema">
<xs:element name="grammys">
<xs:complexType>
<xs:sequence>
    <xs:element name="example">
    <xs:complexType>
    <xs:sequence>
        <xs:element name="esong" type="xs:string"/>
        <xs:element name="ename" type="xs:string"/>
        <xs:element name="ecountry" type="xs:string"/>
        <xs:element name="eyear" type="xs:string"/>
    </xs:sequence>
    </xs:complexType>
    </xs:element>
    <xs:element name="grammy">
    <xs:complexType>
    <xs:sequence>
        <xs:element name="song" type="xs:string"/>
        <xs:element name="name" type="xs:string"/>
        <xs:element name="country" type="xs:string"/>
        <xs:element name="year" type="xs:string"/>
    </xs:sequence>
    </xs:complexType>
    </xs:element>
    <xs:element name="grammy">
    <xs:complexType>
    <xs:sequence>
        <xs:element name="song" type="xs:string"/>
        <xs:element name="name" type="xs:string"/>
        <xs:element name="country" type="xs:string"/>
        <xs:element name="year" type="xs:string"/>
    </xs:sequence>
    </xs:complexType>
    </xs:element>
    <xs:element name="grammy">
    <xs:complexType>
    <xs:sequence>
        <xs:element name="song" type="xs:string"/>
        <xs:element name="name" type="xs:string"/>
        <xs:element name="country" type="xs:string"/>
        <xs:element name="year" type="xs:string"/>
    </xs:sequence>
    </xs:complexType>
    </xs:element>
</xs:sequence>
</xs:complexType>
</xs:element>
</xs:schema>

=== valeryyask/KYAR-1-sem/Лабораторная работа №12/doc3_xml.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<?xml-stylesheet type="text/css" href="forXML.css"?>
<grammys xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="doc3.xsd">
    <example>
        <esong>Песня</esong>
        <ename>Исполнитель</ename>
        <ecountry>Страна</ecountry>
        <eyear>Год</eyear>
    </example>
    <grammy>
        <song>"Just like that"</song>
        <name>Бонни Райт</name>
        <country>США</country>
        <year>2023</year>
    </grammy>
    <grammy>
        <song>"Leave the door open"</song>
        <name>Bruno Mars</name>
        <country>США</country>
        <year>2022</year></grammy>
    <grammy>
        <song>"I can't breathe"</song>
        <name>H.E.R.</name>
        <country>США</country>
        <year>2021</year></grammy>
</grammys>
